try:
    # print (10/0) # will give error
    print(10/1)

except Exception as e:
    print("Invalid Division :" , e)

except Exception as e:
    print("Invalid Division :" , e)

else:
    print("Program run succesfully") # will run when try block runs